In [57]:
import numpy as np

In [58]:
class TicTacToe:
    def __init__(self):
        self.row_count = 3
        self.column_count = 3
        self.action_size = self.row_count * self.column_count

    def get_initial_state(self):
        return np.zeros((self.row_count, self.column_count), dtype=np.int8)

    def get_next_state(self, state, action, player):
        row = action // self.column_count
        column = action % self.column_count

        state[row, column] = player
        return state

    def get_valid_moves(self, state: np.array):
        return (state.reshape(-1) == 0).astype(np.uint8)

    def check_win(self, state, action):
        row = action // self.column_count
        column = action % self.column_count
        player = state[row, column]

        return (
            np.sum(state[row, :]) == player * self.column_count
            or np.sum(state[: column]) == player * self.row_count
            or np.sum(np.diag(state)) == player * self.row_count
            or np.sum(np.diag(np.flip(state, axis=0))) == player * self.row_count
        )
    
    def get_value_and_terminated(self, state, action):
        if self.check_win(state, action):
            return 1, True
        if np.sum(self.get_valid_moves(state)) == 0:
            return 0, True
        return 0, False
    
    def get_opponent(self, player):
        return -player
    
    

In [59]:
ttt = TicTacToe()
state = ttt.get_initial_state()

state = ttt.get_next_state(state, 8, 1)
state = ttt.get_next_state(state, 4, 1)
state = ttt.get_next_state(state, 0, 1)

moves = ttt.get_valid_moves(state)

print(moves)

ttt.get_value_and_terminated(state, 8)



[0 1 1 1 0 1 1 1 0]


(1, True)

In [60]:
arr = np.arange(9)
arr = arr.reshape((3,3))

# np.diag(arr)


arr, arr.diagonal(), np.flip(arr, axis=-1).diagonal()

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([0, 4, 8]),
 array([2, 4, 6]))

In [63]:
import time


ttt = TicTacToe()

player = 1
state = ttt.get_initial_state()

while True:
    print("adjusted state:\n", np.flipud(state))
    valid_moves = ttt.get_valid_moves(state)
    print(f"valid_moves: ", [i + 1 for i in range(ttt.action_size) if valid_moves[i] == 1])

    # need to sleep otherwise sometimes the input pops up before the previous output
    time.sleep(.5)

    action = int(input(f"player {player} move: ")) - 1

    if valid_moves[action] == 0:
        print("action not valid")
        continue

    state = ttt.get_next_state(state, action, player)

    value, is_terminal = ttt.get_value_and_terminated(state, action)
    if is_terminal:
        if value == 1:
            print(f"player {player} won")
        else:
            print("draw")
        print("adjusted state:\n", np.flipud(state))
        print("true state:\n", state)

        break

    player = ttt.get_opponent(player)

adjusted state:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
valid_moves:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
adjusted state:
 [[0 0 1]
 [0 0 0]
 [0 0 0]]
valid_moves:  [1, 2, 3, 4, 5, 6, 7, 8]
adjusted state:
 [[ 0  0  1]
 [ 0  0 -1]
 [ 0  0  0]]
valid_moves:  [1, 2, 3, 4, 5, 7, 8]
adjusted state:
 [[ 0  0  1]
 [ 0  1 -1]
 [ 0  0  0]]
valid_moves:  [1, 2, 3, 4, 7, 8]
adjusted state:
 [[ 0  0  1]
 [ 0  1 -1]
 [ 0  0 -1]]
valid_moves:  [1, 2, 4, 7, 8]
player 1 won
adjusted state:
 [[ 0  0  1]
 [ 0  1 -1]
 [ 1  0 -1]]
true state:
 [[ 1  0 -1]
 [ 0  1 -1]
 [ 0  0  1]]


In [62]:
player = 1

for i in range(10):
    print(f"player: {player}")
    player = player % 2 + 1


player: 1
player: 2
player: 1
player: 2
player: 1
player: 2
player: 1
player: 2
player: 1
player: 2
